### ISSUE TITLE
Issue with arabic language

### ISSUE THREAD

**Issue by monkiki** [bbottema/rtf-to-html#12] opened 2023-08-18 09:13 UTC
The converted text is unreadable:

![image](https://github.com/bbottema/rtf-to-html/assets/130590/0ffeefde-b295-40ac-aa3b-88484afc251a)

**Comment by bbottema** [comment] 2024-05-25 20:03
I think the latest version 1.1.0 may have fixed this. If not, please provide a .msg files that contains this issue.

**Comment by bbottema** [comment] 2024-05-25 20:03
Duplicate of #13 (probably)

**Closed as completed by bbottema** 2024-05-25 20:03 UTC
Labels: bug

**Comment by monkiki** [comment] 2024-05-27 07:21
> I think the latest version 1.1.0 may have fixed this. If not, please provide a .msg files that contains this issue.

Seems to be solved with latest version. 

Thanks!
